version: 2.1

jobs:
  docker-build-and-publish:
    docker:
      - image: cimg/node:22.4
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and Push Docker Image
          working_directory: storefront
          command: |
            if [ "$CIRCLE_BRANCH" = "development" ]; then
              STATIC_TAG="dev"
              BUILD_ARG=$API_URL_DEV
            elif [ "$CIRCLE_BRANCH" = "production" ]; then
              STATIC_TAG="prod"
              BUILD_ARG=$API_URL_PROD
            fi

            UNIQUE_TAG="$STATIC_TAG-$CIRCLE_BUILD_NUM"
            echo "MEDUSA_BACKEND_URL=${STOREFRONT_MEDUSA_BACKEND_URL}" > .env
            echo "NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY}" >> .env
            echo "NEXT_PUBLIC_BASE_URL=${STOREFRONT_NEXT_PUBLIC_BASE_URL}" >> .env
            echo "NEXT_PUBLIC_DEFAULT_REGION=${STOREFRONT_NEXT_PUBLIC_DEFAULT_REGION}" >> .env
            echo "REVALIDATE_SECRET=${NEXTJS_REVALIDATE_SECRET}" >> .env
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            # Build Docker image with build-time ARG for NEXT_PUBLIC_STRAPI_URL
            docker build -t "$DOCKER_USERNAME/liqnic-storefront:$UNIQUE_TAG" .

            docker tag "$DOCKER_USERNAME/liqnic-storefront:$UNIQUE_TAG" "$DOCKER_USERNAME/liqnic-storefront:$STATIC_TAG"
            docker push --all-tags "$DOCKER_USERNAME/liqnic-storefront"

  deploy:
    machine:
      image: ubuntu-2204:current
    steps:
      - run:
          name: Check if container exists
          command: |
            if [ "$CIRCLE_BRANCH" = "development" ]; then
              STATIC_TAG="dev"
              CONTAINER_NAME="liqnic-storefront-dev"
            elif [ "$CIRCLE_BRANCH" = "production" ]; then
              STATIC_TAG="prod"
              CONTAINER_NAME="liqnic-storefront-prod"
            fi
            SSH_COMMAND="SSH_COMMAND="ssh $SSH_USER@$SSH_HOST""
            $SSH_COMMAND "
              if docker ps -a --format '{{.Names}}' | grep -q "${CONTAINER_NAME}"; then
                echo 'Container liqnic-storefront exists'
                docker stop $CONTAINER_NAME
                docker rm $CONTAINER_NAME
                docker rmi $DOCKER_USERNAME/liqnic-storefront:$STATIC_TAG
                echo 'Container liqnic-storefront stopped and removed'
              else
                echo 'Container liqnic-storefront does not exist'
              fi
            "
            
      - run:
          name: Deploy application to VM
          command: |
            if [ "$CIRCLE_BRANCH" = "development" ]; then
              DEPLOY_PATH="/home/docker/liqnic/dev"
            elif [ "$CIRCLE_BRANCH" = "production" ]; then
              DEPLOY_PATH="/home/docker/liqnic/prod"
            fi

            SSH_COMMAND="SSH_COMMAND="ssh $SSH_USER@$SSH_HOST""
            $SSH_COMMAND "
              set -e
              cd $DEPLOY_PATH
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker compose up -d strorefront
              echo '==> storefront deployment complete!'
            "

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - docker-build-and-publish:
          context: [ liqnic-dev, liqnic-prod ]
          filters:
            branches:
              only:
                - development
                - production

      - deploy:
          requires:
            - docker-build-and-publish
          filters:
            branches:
              only:
                - development
                - production
